[package]
name = "totp"
version = "0.1.0"
authors = ["Gergely Brautigam <skarlso777@gmail.com>"]

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
chrono = "0.4"
data-encoding = "2.1.1"
rust-crypto = "^0.2"
byteorder = "1"
